/* Romanizer 罗马音字典 — 手工编校的 Web Coding 名词表 phonetic 数据
 * 风格规则:
 *   - 全小写 ASCII; 重读音节全大写
 *   - 元音: ə→e, ɪ→i, ʌ→u, eɪ→ei, aɪ→ai, aʊ→au, oʊ→o
 *   - tion/sion → shen; ture → cher; sure → zher
 *   - 数组长度 = 音节数,与 syls 数组一一对齐
 *   - 单音节词只有 1 个全大写元素 (=重读)
 * Key: 小写、剥除非字母字符 (与 dictKey(en) 对齐)
 */
window.ROMAJI_DICT = {
  // —— Frontend ——
  "framework":        { syls: ["frame","work"],            romaji: ["FREIM","werk"] },
  "library":          { syls: ["li","bra","ry"],           romaji: ["LAI","bre","ri"] },
  "component":        { syls: ["com","po","nent"],         romaji: ["kem","PO","nent"] },
  "props":            { syls: ["props"],                   romaji: ["PROPS"] },
  "state":            { syls: ["state"],                   romaji: ["STEIT"] },
  "hook":             { syls: ["hook"],                    romaji: ["HUK"] },
  "effect":           { syls: ["ef","fect"],               romaji: ["i","FEKT"] },
  "render":           { syls: ["ren","der"],               romaji: ["REN","der"] },
  "mount":            { syls: ["mount"],                   romaji: ["MAUNT"] },
  "unmount":          { syls: ["un","mount"],              romaji: ["un","MAUNT"] },
  "lifecycle":        { syls: ["life","cy","cle"],         romaji: ["LAIF","sai","kel"] },
  "hydration":        { syls: ["hy","dra","tion"],         romaji: ["hai","DREI","shen"] },
  "slot":             { syls: ["slot"],                    romaji: ["SLOT"] },
  "ref":              { syls: ["ref"],                     romaji: ["REF"] },
  "portal":           { syls: ["por","tal"],               romaji: ["POR","tel"] },
  "fragment":         { syls: ["frag","ment"],             romaji: ["FRAG","ment"] },

  // —— CSS ——
  "selector":         { syls: ["se","lec","tor"],          romaji: ["se","LEK","ter"] },
  "specificity":      { syls: ["spe","ci","fi","ci","ty"], romaji: ["spe","si","FI","si","ti"] },
  "cascade":          { syls: ["cas","cade"],              romaji: ["kas","KEID"] },
  "inheritance":      { syls: ["in","her","i","tance"],    romaji: ["in","HER","i","tens"] },
  "flexbox":          { syls: ["flex","box"],              romaji: ["FLEKS","boks"] },
  "grid":             { syls: ["grid"],                    romaji: ["GRID"] },
  "viewport":         { syls: ["view","port"],             romaji: ["VYU","port"] },
  "responsive":       { syls: ["re","spon","sive"],        romaji: ["ri","SPON","siv"] },
  "breakpoint":       { syls: ["break","point"],           romaji: ["BREIK","point"] },
  "animation":        { syls: ["an","i","ma","tion"],      romaji: ["a","ni","MEI","shen"] },
  "transition":       { syls: ["tran","si","tion"],        romaji: ["tran","ZI","shen"] },
  "position":         { syls: ["po","si","tion"],          romaji: ["pe","ZI","shen"] },
  "cursor":           { syls: ["cur","sor"],               romaji: ["KER","ser"] },

  // —— Build / Bundle ——
  "bundle":           { syls: ["bun","dle"],               romaji: ["BUN","del"] },
  "bundler":          { syls: ["bun","dler"],              romaji: ["BUN","dler"] },
  "build":            { syls: ["build"],                   romaji: ["BILD"] },
  "compile":          { syls: ["com","pile"],              romaji: ["kem","PAIL"] },
  "transpile":        { syls: ["trans","pile"],            romaji: ["TRANS","pail"] },
  "minify":           { syls: ["min","i","fy"],            romaji: ["MIN","i","fai"] },
  "uglify":           { syls: ["ug","li","fy"],            romaji: ["UG","li","fai"] },
  "sourcemap":        { syls: ["source","map"],            romaji: ["SORS","map"] },
  "polyfill":         { syls: ["po","ly","fill"],          romaji: ["PO","li","fil"] },
  "module":           { syls: ["mo","dule"],               romaji: ["MO","jul"] },
  "package":          { syls: ["pack","age"],              romaji: ["PAK","ij"] },
  "dependency":       { syls: ["de","pen","den","cy"],     romaji: ["di","PEN","den","si"] },
  "lockfile":         { syls: ["lock","file"],             romaji: ["LOK","fail"] },
  "monorepo":         { syls: ["mo","no","re","po"],       romaji: ["MO","no","ri","po"] },
  "workspace":        { syls: ["work","space"],            romaji: ["WERK","speis"] },

  // —— JS / TS ——
  "closure":          { syls: ["clo","sure"],              romaji: ["KLO","zher"] },
  "scope":            { syls: ["scope"],                   romaji: ["SKOP"] },
  "hoisting":         { syls: ["hoist","ing"],             romaji: ["HOIST","ing"] },
  "prototype":        { syls: ["pro","to","type"],         romaji: ["PRO","te","taip"] },
  "this":             { syls: ["this"],                    romaji: ["DHIS"] },
  "promise":          { syls: ["pro","mise"],              romaji: ["PRO","mis"] },
  "callback":         { syls: ["call","back"],             romaji: ["KOL","bak"] },
  "generator":        { syls: ["gen","er","a","tor"],      romaji: ["JEN","e","rei","ter"] },
  "iterator":         { syls: ["it","er","a","tor"],       romaji: ["I","te","rei","ter"] },
  "spread":           { syls: ["spread"],                  romaji: ["SPRED"] },
  "destructuring":    { syls: ["de","struc","tu","ring"],  romaji: ["di","STRUK","che","ring"] },
  "generic":          { syls: ["ge","ne","ric"],           romaji: ["je","NE","rik"] },
  "enum":             { syls: ["e","num"],                 romaji: ["I","num"] },
  "interface":        { syls: ["in","ter","face"],         romaji: ["IN","ter","feis"] },
  "decorator":        { syls: ["dec","o","ra","tor"],      romaji: ["DE","ko","rei","ter"] },

  // —— Backend / Server ——
  "server":           { syls: ["ser","ver"],               romaji: ["SER","ver"] },
  "client":           { syls: ["cli","ent"],               romaji: ["KLAI","ent"] },
  "endpoint":         { syls: ["end","point"],             romaji: ["END","point"] },
  "route":            { syls: ["route"],                   romaji: ["RUT"] },
  "middleware":       { syls: ["mid","dle","ware"],        romaji: ["MID","del","wer"] },
  "controller":       { syls: ["con","trol","ler"],        romaji: ["ken","TRO","ler"] },
  "service":          { syls: ["ser","vice"],              romaji: ["SER","vis"] },
  "repository":       { syls: ["re","po","si","to","ry"],  romaji: ["ri","PO","zi","te","ri"] },
  "rest":             { syls: ["rest"],                    romaji: ["REST"] },
  "webhook":          { syls: ["web","hook"],              romaji: ["WEB","huk"] },
  "throttle":         { syls: ["throt","tle"],             romaji: ["THROT","el"] },
  "debounce":         { syls: ["de","bounce"],             romaji: ["di","BAUNS"] },
  "idempotent":       { syls: ["i","dem","po","tent"],     romaji: ["ai","DEM","pe","tent"] },
  "stateless":        { syls: ["state","less"],            romaji: ["STEIT","les"] },
  "stateful":         { syls: ["state","ful"],             romaji: ["STEIT","ful"] },

  // —— Database ——
  "schema":           { syls: ["sche","ma"],               romaji: ["SKI","ma"] },
  "table":            { syls: ["ta","ble"],                romaji: ["TEI","bel"] },
  "row":              { syls: ["row"],                     romaji: ["RO"] },
  "record":           { syls: ["re","cord"],               romaji: ["RE","kord"] },
  "column":           { syls: ["col","umn"],               romaji: ["KO","lem"] },
  "field":            { syls: ["field"],                   romaji: ["FILD"] },
  "index":            { syls: ["in","dex"],                romaji: ["IN","deks"] },
  "query":            { syls: ["que","ry"],                romaji: ["KWE","ri"] },
  "mutation":         { syls: ["mu","ta","tion"],          romaji: ["myu","TEI","shen"] },
  "migration":        { syls: ["mi","gra","tion"],         romaji: ["mai","GREI","shen"] },
  "seed":             { syls: ["seed"],                    romaji: ["SID"] },
  "transaction":      { syls: ["trans","ac","tion"],       romaji: ["tran","ZAK","shen"] },
  "join":             { syls: ["join"],                    romaji: ["JOIN"] },
  "aggregate":        { syls: ["ag","gre","gate"],         romaji: ["A","gre","geit"] },
  "view":             { syls: ["view"],                    romaji: ["VYU"] },
  "trigger":          { syls: ["trig","ger"],              romaji: ["TRI","ger"] },
  "replica":          { syls: ["re","pli","ca"],           romaji: ["RE","pli","ka"] },
  "sharding":         { syls: ["shard","ing"],             romaji: ["SHARD","ing"] },

  // —— Auth / Security ——
  "authentication":   { syls: ["au","then","ti","ca","tion"], romaji: ["aw","then","ti","KEI","shen"] },
  "authorization":    { syls: ["au","tho","ri","za","tion"],  romaji: ["aw","the","rai","ZEI","shen"] },
  "auth":             { syls: ["auth"],                    romaji: ["AWTH"] },
  "oauth":            { syls: ["o","auth"],                romaji: ["O","awth"] },
  "token":            { syls: ["to","ken"],                romaji: ["TO","ken"] },
  "session":          { syls: ["ses","sion"],              romaji: ["SE","shen"] },
  "cookie":           { syls: ["coo","kie"],               romaji: ["KU","ki"] },
  "hash":             { syls: ["hash"],                    romaji: ["HASH"] },
  "salt":             { syls: ["salt"],                    romaji: ["SOLT"] },
  "encryption":       { syls: ["en","cryp","tion"],        romaji: ["en","KRIP","shen"] },

  // —— DevOps / Deploy ——
  "deploy":           { syls: ["de","ploy"],               romaji: ["di","PLOI"] },
  "pipeline":         { syls: ["pipe","line"],             romaji: ["PAIP","lain"] },
  "container":        { syls: ["con","tain","er"],         romaji: ["ken","TEIN","er"] },
  "image":            { syls: ["im","age"],                romaji: ["I","mij"] },
  "registry":         { syls: ["re","gis","try"],          romaji: ["RE","jis","tri"] },
  "orchestration":    { syls: ["or","ches","tra","tion"],  romaji: ["or","kes","TREI","shen"] },
  "cluster":          { syls: ["clus","ter"],              romaji: ["KLUS","ter"] },
  "node":             { syls: ["node"],                    romaji: ["NOD"] },
  "pod":              { syls: ["pod"],                     romaji: ["POD"] },
  "namespace":        { syls: ["name","space"],            romaji: ["NEIM","speis"] },
  "ingress":          { syls: ["in","gress"],              romaji: ["IN","gres"] },
  "canary":           { syls: ["ca","na","ry"],            romaji: ["ke","NE","ri"] },
  "rollback":         { syls: ["roll","back"],             romaji: ["ROL","bak"] },
  "observability":    { syls: ["ob","ser","va","bil","i","ty"], romaji: ["ob","zer","ve","BI","li","ti"] },
  "logging":          { syls: ["log","ging"],              romaji: ["LOG","ing"] },
  "metrics":          { syls: ["me","trics"],              romaji: ["ME","triks"] },
  "tracing":          { syls: ["trac","ing"],              romaji: ["TREIS","ing"] },
  "alert":            { syls: ["a","lert"],                romaji: ["e","LERT"] },

  // —— Cloud / Serverless ——
  "serverless":       { syls: ["ser","ver","less"],        romaji: ["SER","ver","les"] },
  "lambda":           { syls: ["lamb","da"],               romaji: ["LAM","da"] },
  "warm":             { syls: ["warm"],                    romaji: ["WORM"] },
  "region":           { syls: ["re","gion"],               romaji: ["RI","jen"] },
  "bucket":           { syls: ["buck","et"],               romaji: ["BUK","et"] },
  "egress":           { syls: ["e","gress"],               romaji: ["I","gres"] },
  "quota":            { syls: ["quo","ta"],                romaji: ["KWO","ta"] },

  // —— AI / LLM ——
  "prompt":           { syls: ["prompt"],                  romaji: ["PROMPT"] },
  "temperature":      { syls: ["tem","pe","ra","ture"],    romaji: ["TEM","pe","re","cher"] },
  "streaming":        { syls: ["stream","ing"],            romaji: ["STRIM","ing"] },
  "embedding":        { syls: ["em","bed","ding"],         romaji: ["em","BED","ing"] },
  "inference":        { syls: ["in","fer","ence"],         romaji: ["IN","fe","rens"] },
  "hallucination":    { syls: ["hal","lu","ci","na","tion"], romaji: ["he","lu","si","NEI","shen"] },
  "agent":            { syls: ["a","gent"],                romaji: ["EI","jent"] },
  "multimodal":       { syls: ["mul","ti","mo","dal"],     romaji: ["mul","ti","MO","del"] },
  "vision":           { syls: ["vi","sion"],               romaji: ["VI","zhen"] },
  "diarization":      { syls: ["di","ar","i","za","tion"], romaji: ["dai","e","rai","ZEI","shen"] },

  // —— State / Async ——
  "store":            { syls: ["store"],                   romaji: ["STOR"] },
  "reducer":          { syls: ["re","du","cer"],           romaji: ["ri","DYU","ser"] },
  "action":           { syls: ["ac","tion"],               romaji: ["AK","shen"] },
  "dispatch":         { syls: ["dis","patch"],             romaji: ["DIS","pach"] },
  "reactive":         { syls: ["re","ac","tive"],          romaji: ["ri","AK","tiv"] },
  "observable":       { syls: ["ob","ser","va","ble"],     romaji: ["ob","SER","ve","bel"] },
  "subscribe":        { syls: ["sub","scribe"],            romaji: ["seb","SKRAIB"] },
  "publish":          { syls: ["pub","lish"],              romaji: ["PUB","lish"] },
  "microtask":        { syls: ["mi","cro","task"],         romaji: ["MAI","kro","task"] },
  "macrotask":        { syls: ["ma","cro","task"],         romaji: ["MA","kro","task"] },
  "memoization":      { syls: ["me","mo","i","za","tion"], romaji: ["me","mo","ai","ZEI","shen"] },

  // —— Test / Quality ——
  "mock":             { syls: ["mock"],                    romaji: ["MOK"] },
  "stub":             { syls: ["stub"],                    romaji: ["STUB"] },
  "spy":              { syls: ["spy"],                     romaji: ["SPAI"] },
  "fixture":          { syls: ["fix","ture"],              romaji: ["FIKS","cher"] },
  "coverage":         { syls: ["co","ver","age"],          romaji: ["KU","ve","rij"] },
  "regression":       { syls: ["re","gres","sion"],        romaji: ["ri","GRE","shen"] },
  "linter":           { syls: ["lint","er"],               romaji: ["LIN","ter"] },
  "formatter":        { syls: ["for","mat","ter"],         romaji: ["FOR","ma","ter"] },
  "hotfix":           { syls: ["hot","fix"],               romaji: ["HOT","fiks"] },
  "patch":            { syls: ["patch"],                   romaji: ["PACH"] },
  "refactor":         { syls: ["re","fac","tor"],          romaji: ["ri","FAK","ter"] },

  // —— Git ——
  "commit":           { syls: ["com","mit"],               romaji: ["ke","MIT"] },
  "branch":           { syls: ["branch"],                  romaji: ["BRANCH"] },
  "merge":            { syls: ["merge"],                   romaji: ["MERJ"] },
  "rebase":           { syls: ["re","base"],               romaji: ["ri","BEIS"] },
  "stash":            { syls: ["stash"],                   romaji: ["STASH"] },
  "pull":             { syls: ["pull"],                    romaji: ["PUL"] },
  "fetch":            { syls: ["fetch"],                   romaji: ["FECH"] },
  "push":             { syls: ["push"],                    romaji: ["PUSH"] },
  "clone":            { syls: ["clone"],                   romaji: ["KLON"] },
  "fork":             { syls: ["fork"],                    romaji: ["FORK"] },
  "diff":             { syls: ["diff"],                    romaji: ["DIF"] },
  "conflict":         { syls: ["con","flict"],             romaji: ["KON","flikt"] },
  "tag":              { syls: ["tag"],                     romaji: ["TAG"] },
  "squash":           { syls: ["squash"],                  romaji: ["SKWOSH"] },
  "amend":            { syls: ["a","mend"],                romaji: ["e","MEND"] },
  "blame":            { syls: ["blame"],                   romaji: ["BLEIM"] },
  "submodule":        { syls: ["sub","mo","dule"],         romaji: ["SUB","mo","jul"] },
  "worktree":         { syls: ["work","tree"],             romaji: ["WERK","tri"] },

  // —— HTTP / Browser ——
  "header":           { syls: ["head","er"],               romaji: ["HED","er"] },
  "body":             { syls: ["bo","dy"],                 romaji: ["BO","di"] },
  "payload":          { syls: ["pay","load"],              romaji: ["PEI","lod"] },
  "origin":           { syls: ["o","ri","gin"],            romaji: ["O","ri","jin"] },
  "manifest":         { syls: ["ma","ni","fest"],          romaji: ["MA","ni","fest"] },

  // —— Patterns ——
  "singleton":        { syls: ["sin","gle","ton"],         romaji: ["SIN","gel","ten"] },
  "factory":          { syls: ["fac","to","ry"],           romaji: ["FAK","te","ri"] },
  "observer":         { syls: ["ob","ser","ver"],          romaji: ["ob","SER","ver"] },
  "adapter":          { syls: ["a","dap","ter"],           romaji: ["e","DAP","ter"] },
  "facade":           { syls: ["fa","cade"],               romaji: ["fe","SAD"] },
  "strategy":         { syls: ["stra","te","gy"],          romaji: ["STRA","te","ji"] },
  "proxy":            { syls: ["prox","y"],                romaji: ["PROK","si"] },
  "composition":      { syls: ["com","po","si","tion"],    romaji: ["kom","pe","ZI","shen"] },

  // —— Workflow / Process ——
  "spike":            { syls: ["spike"],                   romaji: ["SPAIK"] },
  "backlog":          { syls: ["back","log"],              romaji: ["BAK","log"] },
  "sprint":           { syls: ["sprint"],                  romaji: ["SPRINT"] },
  "standup":          { syls: ["stand","up"],              romaji: ["STAND","up"] },
  "retro":            { syls: ["ret","ro"],                romaji: ["RET","ro"] },
  "kanban":           { syls: ["kan","ban"],               romaji: ["KAN","ban"] },
  "incident":         { syls: ["in","ci","dent"],          romaji: ["IN","si","dent"] },
  "postmortem":       { syls: ["post","mor","tem"],        romaji: ["post","MOR","tem"] },
  "triage":           { syls: ["tri","age"],               romaji: ["TRI","aj"] },
  "spec":             { syls: ["spec"],                    romaji: ["SPEK"] },
  "changelog":        { syls: ["change","log"],            romaji: ["CHEINJ","log"] },
  "semver":           { syls: ["sem","ver"],               romaji: ["SEM","ver"] },
  "release":          { syls: ["re","lease"],              romaji: ["ri","LIS"] },

  // —— Misc useful (常见词) ——
  "asynchronous":     { syls: ["a","syn","chro","nous"],   romaji: ["ei","SIN","kre","nes"] },
  "synchronous":      { syls: ["syn","chro","nous"],       romaji: ["SIN","kre","nes"] },
  "async":            { syls: ["a","sync"],                romaji: ["EI","sink"] },
  "sync":             { syls: ["sync"],                    romaji: ["SINK"] },
  "await":            { syls: ["a","wait"],                romaji: ["e","WEIT"] },
  "encapsulation":    { syls: ["en","cap","su","la","tion"], romaji: ["en","kap","su","LEI","shen"] },
  "generalization":   { syls: ["ge","ne","ra","li","za","tion"], romaji: ["je","ne","re","li","ZEI","shen"] },
  "serialization":    { syls: ["se","ri","a","li","za","tion"], romaji: ["si","ri","e","li","ZEI","shen"] },
  "phenomenon":       { syls: ["phe","no","me","non"],     romaji: ["fe","NO","me","non"] },
  "superficiality":   { syls: ["su","per","fi","ci","a","li","ty"], romaji: ["su","per","fi","shi","a","LI","ti"] }
};
